import { Derivation } from '../derivations';
import { HDOptionsInterface } from '../interfaces';
export declare class HD {
    protected derivation: any;
    constructor(options?: HDOptionsInterface);
    static getName(): string;
    getName(): string;
    fromSeed(...args: any[]): this;
    fromXPrivateKey(...args: any[]): this;
    fromXPublicKey(...args: any[]): this;
    fromWIF(wif: string): this;
    fromPrivateKey(privateKey: string): this;
    fromSpendPrivateKey(spendPrivateKey: string): this;
    fromPublicKey(publicKey: string): this;
    fromWatchOnly(viewPrivateKey: string, spendPublicKey: string): this;
    fromDerivation(derivation: Derivation): this;
    updateDerivation(derivation: Derivation): this;
    cleanDerivation(): this;
    getDerivation(): Derivation;
    getSeed(): string | null;
    getSemantic(): string | null;
    getRootXPrivateKey(...args: any[]): string | null;
    getRootXPublicKey(...args: any[]): string | null;
    getMasterXPrivateKey(...args: any[]): string | null;
    getMasterXPublicKey(...args: any[]): string | null;
    getRootPrivateKey(...args: any[]): string | null;
    getRootWIF(...args: any[]): string | null;
    getRootChainCode(): string | null;
    getRootPublicKey(...args: any[]): string | null;
    getMasterPrivateKey(...args: any[]): string | null;
    getMasterWIF(...args: any[]): string | null;
    getMasterChainCode(...args: any[]): string | null;
    getMasterPublicKey(...args: any[]): string | null;
    getXPrivateKey(...args: any[]): string | null;
    getXPublicKey(...args: any[]): string | null;
    getPrivateKey(...args: any[]): string | null;
    getStrict(): boolean | null;
    getSpendPrivateKey(): string | null;
    getViewPrivateKey(): string;
    getWIF(..._args: any[]): string | null;
    getWIFType(): any;
    getChainCode(): any;
    getPublicKey(...args: any[]): any;
    getCompressed(): string;
    getUncompressed(): string;
    getSpendPublicKey(): string;
    getViewPublicKey(): string;
    getPublicKeyType(): string;
    getMode(): string;
    getHash(): string;
    getFingerprint(): string;
    getParentFingerprint(): any;
    getDepth(): number;
    getPath(): string;
    getPathKey(): string | null;
    getIndex(): number;
    getIndexes(): number[];
    getIntegratedAddress(...args: any[]): string | null;
    getPrimaryAddress(...args: any[]): string;
    getSubAddress(...args: any[]): string;
    getAddress(...args: any[]): string | null;
}
//# sourceMappingURL=hd.d.ts.map