import * as info from './info';
import * as consts from './consts';
import * as crypto from './crypto';
import * as utils from './utils';
import * as cryptocurrencies from './cryptocurrencies';
import * as entropies from './entropies';
import * as mnemonics from './mnemonics';
import * as seeds from './seeds';
import * as eccs from './eccs';
import * as derivations from './derivations';
import * as hds from './hds';
import * as addresses from './addresses';
import { HDWallet } from './hdwallet';
declare const hdwallet: {
    info: typeof info;
    consts: typeof consts;
    crypto: typeof crypto;
    utils: typeof utils;
    cryptocurrencies: typeof cryptocurrencies;
    entropies: typeof entropies;
    mnemonics: typeof mnemonics;
    seeds: typeof seeds;
    eccs: typeof eccs;
    derivations: typeof derivations;
    hds: typeof hds;
    addresses: typeof addresses;
    HDWallet: typeof HDWallet;
};
export { hdwallet, info, consts, crypto, utils, cryptocurrencies, entropies, mnemonics, seeds, eccs, derivations, hds, addresses, HDWallet };
//# sourceMappingURL=index.d.ts.map